#!/bin/bash
#
# This script populates the data directory (default located in data/)
#
# Usage example:
# ./create_data.sh --force --data-dir ./data --storage-path /hpcperm/papa/inp_db_coloc_STORAGE
#
# Parse options
# --help, -h, --help   Show this help message and exit
#
# --clean, -c          Clean the data directory and exit
#
# --force, -f          Force overwrite of existing data files
#
# --data-dir, -d:      Specify the data directory (default: ./data)
#
# --storage-path, -s   Specify where the data stored data are located
#
# --active-path, -a    Specify where the active data are located.
#                      These contain symlinks to the storage paths and will contain files generated by the inpdb_colocator.
#                      Its content is normally only a few hundred MB, but location can be specified to a custom filesystem to avoid filling up the home directory.
#                      If not specified, the default is to use the data directory.
#

set -euo pipefail

# Help message
print_help() {
    sed -n '/^#/!q;/^#!/!p' "$0" | sed 's/^ *#//'
}

while [[ $# -gt 0 ]]; do
  case $1 in
    --help|-h)
      print_help
      exit 0
      ;;
    --clean|-c)
      CLEAN_AND_QUIT=true
      shift
      ;;
    --force|-f)
      FORCE_OVERWRITE=true
      shift
      ;;
    --data-dir|-d)
      DATA_DIR="$2"
      shift 2
      ;;
    --storage-path|-s)
      STORAGE_PATH="$2"
      shift 2
      ;;
    --active-path|-a)
      ACTIVE_PATH="$2"
      shift 2
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

# Set default values if not provided
DATA_DIR="${DATA_DIR:-./data}"
ACTIVE_PATH="${ACTIVE_PATH:-$DATA_DIR}"
FORCE_OVERWRITE="${FORCE_OVERWRITE:-false}"

declare -a subdirs=("aeronet" "cams_clim" "cams_free" "era5" "inp_db" "macv2_sp" "merra2" "volc_aero")
declare -a subdirs_passive=("cams_free" "era5" "volc_aero")
declare -a subdirs_active=("cams_clim" "macv2_sp" "merra2")
declare -a subdirs_follow=("aeronet" "inp_db")

#echo "Cleaning data directory '$DATA_DIR'"
for subdir in "${subdirs[@]}"; do
  target_dir_data="$DATA_DIR/$subdir"
  if [ -d "$target_dir_data" ]; then
    rm -rf "$target_dir_data"
  fi
done
echo "'$DATA_DIR' cleaned."
if [ "$(realpath "$ACTIVE_PATH")" != "$(realpath "$DATA_DIR")" ]; then
  #echo "Cleaning active path '$ACTIVE_PATH'"
  for subdir in "${subdirs[@]}"; do
    target_dir="$ACTIVE_PATH/$subdir"
    if [ -d "$target_dir" ]; then
      rm -rf "$target_dir"
    fi
  done
  echo "'$ACTIVE_PATH' cleaned."
fi
if [ "${CLEAN_AND_QUIT:-false}" == "true" ]; then
  exit 0
fi

# Storage path is provided and exists?
if [ "${STORAGE_PATH:-}" == "" ]; then
  echo "Error: --storage-path is required."
  exit 1
fi
if [ ! -d "$STORAGE_PATH" ]; then
  echo "Error: Storage path '$STORAGE_PATH' does not exist."
  exit 1
fi

for subdir in "${subdirs[@]}"; do
  target_dir="$ACTIVE_PATH/$subdir"
  storage_dir="$STORAGE_PATH/$subdir"

  # Check if the storage directory exists
  if [ ! -d "$storage_dir" ]; then
    echo "Warning: Storage directory '$storage_dir' does not exist."
    continue
  fi

  # Create the target directory and symlink to the storage path
  mkdir -p "$target_dir"

  # passive subdirs: symlink all archives contained in the storage
  if [[ " ${subdirs_passive[@]} " =~ " ${subdir} " ]]; then
    for file in "$storage_dir"/*; do
      if [ -f "$file" ]; then
        ln -sf "$file" "$target_dir/"
      elif [ ${file##*_} == "zarr" ]; then
        ln -sf "$file" "$target_dir/"
      fi
    done
  fi

  # Active subdirs: symlink content and create subdirectory for generated data
  if [[ " ${subdirs_active[@]} " =~ " ${subdir} " ]]; then
    for file in "$storage_dir"/*; do
      if [ -f "$file" ]; then
        ln -sf "$file" "$target_dir/"
      fi
    done
    mkdir -p "$target_dir/point_files"
  fi

  # Follow subdirs: recursively recreate directory structure and symlink files
  # Create synth_files directory in leaf directories
  if [[ " ${subdirs_follow[@]} " =~ " ${subdir} " ]]; then
    find "$storage_dir" -type d | while read -r dir; do
      mkdir -p "${dir/$storage_dir/$target_dir}"
  done
  find "$storage_dir" -type d -links 2 | while read -r dir; do
    mkdir -p "${dir/$storage_dir/$target_dir}/synth_files"
  done
  find "$storage_dir" -type f | while read -r src; do
    dst="${src/$storage_dir/$target_dir}"
    ln -sf "$src" "$dst"
  done
  fi
done

# If active path is not datadir, create symlinks to the active path
if [ "$(realpath "$ACTIVE_PATH")" != "$(realpath "$DATA_DIR")" ]; then
  for subdir in "${subdirs[@]}"; do
    target_dir="$DATA_DIR/$subdir"
    active_dir="$ACTIVE_PATH/$subdir"
    if [ ! -d "$active_dir" ]; then
      echo "Warning: Target directory '$target_dir' does not exist. Skipping symlink creation for active path."
      continue
    fi
    ln -sf "$(realpath "$active_dir")" "$target_dir"
  done
fi